# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode9.4
xcode_project: JNBTopbar.xcodeproj
# xcode_workspace: <WORKSPACE_PLACEHOLDER>
xcode_scheme: JNBTopbar
xcode_sdk: iphonesimulator10.0
env:
  global:
    - FRAMEWORK_NAME=JNBTopbar
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - carthage bootstrap
before_deploy:
  - carthage build --no-skip-current
  - carthage archive JNBTopbar
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/JNBTopbar.xcworkspace -scheme JNBTopbar-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
