# references:

# * https://www.objc.io/issues/6-build-tools/travis-ci/


osx_image: xcode9.1
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
#  - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/JNBTopbar.xcworkspace -scheme JNBTopbar-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.1' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

